name: Linux builds

on: [push, pull_request]

env:
  CCACHE_DIR:      "/dev/shm/.ccache"
  CCACHE_MAXSIZE:  "64M"
  CCACHE_COMPRESS: "true"

jobs:
  build_ubuntu:
    name: ${{ matrix.conf.name }}
    runs-on: ${{ matrix.conf.os }}
    if: github.event_name != 'pull_request' || contains('dreamer,kcgen,ant-222', github.actor) == false
    strategy:
      max-parallel: 4
      matrix:
        conf:
          # - name: GCC, Ubuntu 16.04
          #   os: ubuntu-16.04
          #   flags: -c gcc
          #   max_warnings: 24
          - name: GCC, Ubuntu 18.04 (ARM test)
            os: ubuntu-18.04
            flags: -c gcc
            max_warnings: 26
          # - name: GCC, Ubuntu 20.04
          #   os: ubuntu-20.04
          #   flags: -c gcc
          #   max_warnings: 26
          # - name: Clang, Ubuntu 20.04
          #   os: ubuntu-20.04
          #   flags: -c clang -v 10
          #   max_warnings: 9
          # - name: Ubuntu, +debug
          #   os: ubuntu-latest
          #   flags: -c gcc
          #   config_flags: --enable-debug
          #   max_warnings: 137
          # - name: Ubuntu, -dyn_x86, +dynrec
          #   os: ubuntu-latest
          #   flags: -c gcc
          #   config_flags: --disable-dynamic-x86
          #   max_warnings: 33

    steps:
      - uses: actions/checkout@v2
      - run:  sudo apt-get update
      - name: Install C++ compiler and libraries
        run:  sudo apt-get install -y $(./scripts/list-build-dependencies.sh -m apt ${{ matrix.conf.flags }})
      - name: Log environment
        run:  ./scripts/log-env.sh
      - name: Build
        run:  ./scripts/build.sh -t Debug ${{ matrix.conf.flags }} ${{ matrix.conf.config_flags }}
      - name: Summarize warnings
        env:
          MAX_WARNINGS: ${{ matrix.conf.max_warnings }}
        run:  ./scripts/count-warnings.py build.log

